version: '3'
services:
  nsk-koa:
    build:
      context: .
      dockerfile: ./test/Dockerfile
    command: npm run coverage
    environment:
      DEBUG: app-container*
      NODE_CONFIG_DIR: /home/app/test/config
      NODE_ENV: test
    ports:
      - 9002:9002
    volumes:
      - ./coverage:/home/app/coverage
      - ./src:/home/app/src
      - ./test:/home/app/test
      - ./package.json:/home/app/package.json
      - /home/app/node_modules
