version: '2'
services:
  nsk-koa:
    build:
      context: .
      dockerfile: ./test/Dockerfile
      args:
        NPM_TOKEN: $NPM_TOKEN
    command: npm run coverage
    environment:
      NODE_CONFIG_DIR: /opt/app/test/config
      DEBUG: app-container*
      NODE_ENV: test
    ports:
      - "9004:9004"
    volumes:
      - ./coverage:/opt/app/coverage
      - ./src:/opt/app/src
      - ./test:/opt/app/test
