version: '3'
services:
  nsk-koa:
    build:
      context: .
      dockerfile: ./test/Dockerfile
    command: npm run coverage
    environment:
      DEBUG: app-container*
      NODE_CONFIG_DIR: /opt/app/test/config
      NODE_ENV: test
    ports:
      - 9002:9002
    volumes:
      - ./coverage:/opt/app/coverage
      - ./src:/opt/app/src
      - ./test:/opt/app/test
