version: '2'
services:
  nsk-koa:
    build:
      context: .
      dockerfile: ./test/Dockerfile
      args:
        NPM_TOKEN: $NPM_TOKEN
    command: npm run coverage
    environment:
      NODE_ENV: test
    volumes:
      - ./coverage:/opt/app/coverage
      - ./src:/opt/app/src
      - ./test:/opt/app/test
