version: '2'
services:
  nsk-koa:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: npm run coverage
    environment:
      NODE_ENV: test
    volumes:
     - .:/home/app/src
     - /home/app/src/node_modules
